POST http://localhost:3333/api/makanan_step
Content-Type: application/json

{
  "makananId": 1,
  "stepId": 1
}

# Delete a relationship between makanan and step
DELETE http://localhost:3333/makanan_step/1
