# GET All
GET http://localhost:5500/api
Content-Type: application/json

###

# GET ID
GET http://localhost:5500/api/1
Content-Type: application/json

###

# POST 
POST http://localhost:5500/api/
Content-Type: application/json

{
  "title": "Pentingkah Konsumsi Makanan Bergizi Seimbang",
  "description": "Sistem imunitas atau sistem kekebalan tubuh merupakan sistem pertahanan alami yang bertugas untuk melindungi tubuh dari serangan patogen atau kuman (virus, bakteri, jamur).",
  "link": "https://dinkes.jogjaprov.go.id/berita/detail/gizi-dan-imunitas-pentingkah-konsumsi-makanan-bergizi-seimbang",
  "image": "https://firebasestorage.googleapis.com/v0/b/song-e806c.appspot.com/o/News%2Fnews5.png?alt=media&token=0639585e-b379-400c-8c64-5b02ad284a1b"
}

###

# DELETE
DELETE http://localhost:5500/api/7
Content-Type: application/json