# GET All
GET http://localhost:5500/api/healthyfy
Content-Type: application/json

###

# GET ID
GET http://localhost:5500/api/1
Content-Type: application/json

###

# POST 
POST http://localhost:5500/api/
Content-Type: application/json

{
  "title": "Sample News Title",
  "description": "This is a sample news description",
  "link": "http://example.com/news",
  "image": "http://example.com/image.jpg"
}

###

# DELETE
DELETE http://localhost:5500/api/4
Content-Type: application/json